# Generated by Django 4.0.4 on 2022-06-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_email_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
